//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EatFood {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EatFood.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add food place.
        /// </summary>
        public static string Adding {
            get {
                return ResourceManager.GetString("Adding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adress .
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adress:.
        /// </summary>
        public static string Adress2 {
            get {
                return ResourceManager.GetString("Adress2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adress:.
        /// </summary>
        public static string AdressText {
            get {
                return ResourceManager.GetString("AdressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bar.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cafe.
        /// </summary>
        public static string Cafe {
            get {
                return ResourceManager.GetString("Cafe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chose option.
        /// </summary>
        public static string ChoseOption {
            get {
                return ResourceManager.GetString("ChoseOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Count of food places types.
        /// </summary>
        public static string CountDiagram {
            get {
                return ResourceManager.GetString("CountDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Info about development.
        /// </summary>
        public static string data {
            get {
                return ResourceManager.GetString("data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fastfood.
        /// </summary>
        public static string Fastfood {
            get {
                return ResourceManager.GetString("Fastfood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For all peope.
        /// </summary>
        public static string ForWhom {
            get {
                return ResourceManager.GetString("ForWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Main idea.
        /// </summary>
        public static string idea {
            get {
                return ResourceManager.GetString("idea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Development info.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на App information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Places List.
        /// </summary>
        public static string ListHeader {
            get {
                return ResourceManager.GetString("ListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mid price of food places.
        /// </summary>
        public static string MidDiagram {
            get {
                return ResourceManager.GetString("MidDiagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Number: 000-00-00.
        /// </summary>
        public static string num {
            get {
                return ResourceManager.GetString("num", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Adding new food place.
        /// </summary>
        public static string PageAddHeader {
            get {
                return ResourceManager.GetString("PageAddHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mid price is.
        /// </summary>
        public static string PriceText {
            get {
                return ResourceManager.GetString("PriceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mid price:.
        /// </summary>
        public static string PriceText2 {
            get {
                return ResourceManager.GetString("PriceText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Developed by microsoft.
        /// </summary>
        public static string Prog {
            get {
                return ResourceManager.GetString("Prog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rating:.
        /// </summary>
        public static string Rating2 {
            get {
                return ResourceManager.GetString("Rating2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Restoraunt.
        /// </summary>
        public static string Restoraunt {
            get {
                return ResourceManager.GetString("Restoraunt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show food places.
        /// </summary>
        public static string Showing {
            get {
                return ResourceManager.GetString("Showing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It is start page. Welcome!.
        /// </summary>
        public static string StartPageText {
            get {
                return ResourceManager.GetString("StartPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show stats.
        /// </summary>
        public static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string StatsHeader {
            get {
                return ResourceManager.GetString("StatsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Input data.
        /// </summary>
        public static string TextAddingTop {
            get {
                return ResourceManager.GetString("TextAddingTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can see list and information about food places or add your! Start. Swipe menu in left!.
        /// </summary>
        public static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type:.
        /// </summary>
        public static string Type2 {
            get {
                return ResourceManager.GetString("Type2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Typical food.
        /// </summary>
        public static string TypicalFood {
            get {
                return ResourceManager.GetString("TypicalFood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Typical food:.
        /// </summary>
        public static string TypicalFood2 {
            get {
                return ResourceManager.GetString("TypicalFood2", resourceCulture);
            }
        }
    }
}
